### ISSUE TITLE
Unable to connect to s3: 'utf8' codec can't decode byte 0xef in position 8213: invalid continuation byte

### ISSUE THREAD

**Issue by jackstuard** [bloomreach/s4cmd#130]
Hi, recently I'm getting this exception when calling s4cmd, any ideas? It was working few weeks ago, nothing was changed (packages installed, etc).

[Runtime Exception] Unable to connect to s3: 'utf8' codec can't decode byte 0xef in position 8213: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 1981, in <module>
    CommandHandler(opt).run(args)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 1605, in run
    CommandHandler.__dict__[cmd + '_handler'](self, args)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 134, in wrapper
    ret = func(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 1738, in dsync_handler
    self.s3handler().dsync_files(source, target, args)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 1611, in s3handler
    return S3Handler(self.opt)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 701, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 715, in connect
    raise RetryFailure('Unable to connect to s3: %s' % e)
RetryFailure: Unable to connect to s3: 'utf8' codec can't decode byte 0xef in position 8213: invalid continuation byte

**Comment by navinpai** [comment]
What command did you get this error on? Looks like dsync as per the log you've shared, but wanted to confirm. Could you share the command please?

**Comment by jackstuard** [comment]
Exactly,
/usr/sbin/s4cmd dsync /var/www/images s3://mys3 -c 8

**Comment by navinpai** [comment]
This looks like an issue with boto3 (though I'm still investigating this). Can you please run the following and let me know if this works for you wthout throwing an error?

```
import boto3
boto3.__version__
client1 = boto3.client('s3',aws_access_key_id=your_aws_access_key_id, your_aws_secret_access_key=aws_secret_access_key)
```
Also, we made a release for s4cmd 2-3 days back. There are no changes (AFAICT) related to boto3 in the release, but would be helpful to upgrade so that we can check against the latest release. To upgrade, use `pip install --upgrade s4cmd` _(assuming you installed using pip)_

**Comment by jackstuard** [comment]
Thanks, here it the result:
Traceback (most recent call last):
  File "teste.py", line 3, in <module>
    client1 = boto3.client('s3',aws_access_key_id='myKey', aws_secret_access_key='my_secret')
  File "/usr/local/lib/python2.7/dist-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 851, in create_client
    endpoint_resolver = self.get_component('endpoint_resolver')
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 726, in get_component
    return self._components.get_component(name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 922, in get_component
    self._components[name] = factory()
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 189, in create_default_resolver
    endpoints = loader.load_data('endpoints')
  File "/usr/local/lib/python2.7/dist-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/loaders.py", line 420, in load_data
    found = self.file_loader.load_file(possible_path)
  File "/usr/local/lib/python2.7/dist-packages/botocore/loaders.py", line 173, in load_file
    payload = fp.read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xef in position 8213: invalid continuation byte

I will try to update to the last changes and let you know the results.

**Comment by navinpai** [comment]
As expected, it's a boto3 exception as your log shows. Updating s4cmd would not help since it would continue to use the old boto3 version only. You might want to try upgrading boto3 using:

```
pip install --upgrade boto3
```
... and then try the same commands. If the issue still continues, raise an issue on the boto3 github: https://github.com/boto/boto3/issues.

Will close this issue since it's not an s4cmd issue but a boto3 issue AFAICT
