### ISSUE TITLE
ERROR: Part number must be an integer between 1 and 10000, inclusive

### ISSUE THREAD

**Issue by dougreed765** [bloomreach/s4cmd#143]
Hi

Running S4cmd Version 2.1.0 on Centos 7

Trying to upload a very big file (529,168,322,560) and get the following messages

[Exception] An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
Exception in thread Thread-121:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/bin/s4cmd.py", line 542, in run
    fail('[Exception] ', exc_info=e)
  File "/usr/bin/s4cmd.py", line 189, in fail
    raise RuntimeError(status)
RuntimeError: 1

[Thread Failure] An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
[Runtime Exception] 1
Traceback (most recent call last):
  File "/usr/bin/s4cmd.py", line 1928, in main
    CommandHandler(opt).run(args)
  File "/usr/bin/s4cmd.py", line 1557, in run
    CommandHandler.__dict__[cmd + '_handler'](self, args)
  File "/usr/bin/s4cmd.py", line 129, in wrapper
    ret = func(*args, **kargs)
  File "/usr/bin/s4cmd.py", line 1655, in put_handler
    self.s3handler().put_files(source, target)
  File "/usr/bin/s4cmd.py", line 129, in wrapper
    ret = func(*args, **kargs)
  File "/usr/bin/s4cmd.py", line 821, in put_files
    pool.join()
  File "/usr/bin/s4cmd.py", line 594, in join
    self.tasks.join()
  File "/usr/bin/s4cmd.py", line 469, in join
    fail('[Thread Failure] ', exc_info=self.exc_info)
  File "/usr/bin/s4cmd.py", line 189, in fail
    raise RuntimeError(status)
RuntimeError: 1

Any ideas?

Many thanks

**Comment by navinpai** [comment]
Hey!

The part limit is an AWS S3 part limitation (A file can have only [upto 10000 parts](https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html)). The way to get past this is by changing the size of the part size. 

By default s4cmd uses 50MB part sizes (https://github.com/bloomreach/s4cmd/blob/master/s4cmd.py#L1888). You can use the `--multipart-split-size` param with a larger number (note the param accepts size "in bytes") to give a larger number and you should be good to go! 👍 

I'll close this issue for now, but if the solution doesn't work for you, please comment/reopen. Thanks for using s4cmd!
