### ISSUE TITLE
Just does not work

### ISSUE THREAD

**Issue by socketpair** [bloomreach/s4cmd#168]
```
cat ~/.s3cfg
[default]
access_key = XXXXXX-YYYYYYYYYYYYY
secret_key = tPVsgEQuKnVjknvr6dBvieVrsJK2afudeh1-GGu5
bucket_location = ru-central1
host_base = storage.yandexcloud.net
host_bucket = %(bucket)s.storage.yandexcloud.net
website_endpoint = http://%(bucket)s.website.yandexcloud.net
```
s3cmd works. s4cmd:

```
  (D)s4cmd:662  read S3 keys from $HOME/.s3cfg file
  (D)s4cmd:135  >> ls_handler(<__main__.CommandHandler object at 0x7f0966afc650>, ['ls'])
  (D)s4cmd:135  >> list_buckets(<__main__.S3Handler object at 0x7f0966afc5d0>)
  (D)s4cmd:405  >> S3APICALL list_buckets()
  (E)s4cmd:189  [Runtime Exception] An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.
  (E)s4cmd:191  Traceback (most recent call last):
  File "/usr/bin/s4cmd", line 1878, in <module>
    CommandHandler(opt).run(args)
  File "/usr/bin/s4cmd", line 1533, in run
    CommandHandler.__dict__[cmd + '_handler'](self, args)
  File "/usr/bin/s4cmd", line 136, in wrapper
    ret = func(*args, **kargs)
  File "/usr/bin/s4cmd", line 1604, in ls_handler
    self.pretty_print(self.s3handler().list_buckets())
  File "/usr/bin/s4cmd", line 136, in wrapper
    ret = func(*args, **kargs)
  File "/usr/bin/s4cmd", line 698, in list_buckets
    for bucket in self.s3.list_buckets().get('Buckets') or []:
  File "/usr/bin/s4cmd", line 406, in wrapped_method
    ret = getattr(self.client, method)(*args, **merged_kargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 622, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.
```

s4cmd 2.0.1+ds-1

**Comment by jordan26** [comment]
Make sure to define the `endpoint_url` too with your commands.
