### ISSUE TITLE
Does not work - reproducible test inside :)

### ISSUE THREAD

**Issue by brettswift** [bloomreach/s4cmd#178]
1. `docker run -it --rm -v ~/.aws:/root/.aws -v "$PWD":/src python:3 bash`
2. `pip install s4cmd`
3. `s4cmd du`

gives me: 

```
root@08845dcf8166:/# s4cmd du -r
[Runtime Failure] Source doesn't exist.
[Runtime Exception] 1
Traceback (most recent call last):
  File "/usr/local/bin/s4cmd.py", line 1928, in main
    CommandHandler(opt).run(args)
  File "/usr/local/bin/s4cmd.py", line 1557, in run
    CommandHandler.__dict__[cmd + '_handler'](self, args)
  File "/usr/local/bin/s4cmd.py", line 129, in wrapper
    ret = func(*args, **kargs)
  File "/usr/local/bin/s4cmd.py", line 1736, in du_handler
    for src, size in self.s3handler().size(args[1:]):
  File "/usr/local/bin/s4cmd.py", line 129, in wrapper
    ret = func(*args, **kargs)
  File "/usr/local/bin/s4cmd.py", line 1049, in size
    for src in self.source_expand(source):
  File "/usr/local/bin/s4cmd.py", line 782, in source_expand
    fail("[Runtime Failure] Source doesn't exist.")
  File "/usr/local/bin/s4cmd.py", line 189, in fail
    raise RuntimeError(status)
RuntimeError: 1
```

good luck!

**Comment by debodirno** [comment]
`s4cmd du` takes an S3 path. It results in `RuntimeError` because this case is not gracefully handled.
I am closing this issue and creating another issue for making graceful exits to the `du` command.
