### ISSUE TITLE
Error: S4cmd : An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive

### ISSUE THREAD

**Issue by The-Prasun** [bloomreach/s4cmd#238]
Hi,
I am trying to upload a 560 GB file to s3 bucket and it's failing with below error.

```
[Exception] An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/bin/s4cmd.py", line 542, in run
    fail('[Exception] ', exc_info=e)
  File "/usr/local/bin/s4cmd.py", line 189, in fail
    raise RuntimeError(status)
RuntimeError: 1

[Exception] An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/bin/s4cmd.py", line 542, in run
    fail('[Exception] ', exc_info=e)
  File "/usr/local/bin/s4cmd.py", line 189, in fail
    raise RuntimeError(status)
RuntimeError: 1
```

**Comment by dbeal-eth** [comment]
since this ticket is old, I think I should comment that this appears to still be an issue (just occurred for me today)

**Comment by AlexandrT** [comment]
AWS (as many others s3-like storages) recommends not to exceed 10,000 parts in multipart upload - https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html
