### ISSUE TITLE
Trouble connecting to TrueNAS SCALE with minio and self signed cert

### ISSUE THREAD

**Issue by stevenmcastano** [bloomreach/s4cmd#315]
I'm able to get `s3cmd` to work find. lists buckets, uploads, downloads, everything... but when I used the exact same command with s4cmd I get the following error:

```
root@nas002:~# s4cmd ls s3://testing
[Exception] An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
Exception in thread Thread-1:ad(s)]
[Thread Failure] An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
Traceback (most recent call last):
  File "/usr/local/bin/s4cmd.py", line 520, in run
[Runtime Exception] 1
    self.__class__.__dict__[func_name](self, *args, **kargs)
  File "/usr/local/bin/s4cmd.py", line 129, in wrapper
    ret = func(*args, **kargs)
Traceback (most recent call last):
  File "/usr/local/bin/s4cmd.py", line 1928, in main
    CommandHandler(opt).run(args)
  File "/usr/local/bin/s4cmd.py", line 1557, in run
    CommandHandler.__dict__[cmd + '_handler'](self, args)
  File "/usr/local/bin/s4cmd.py", line 129, in wrapper
    ret = func(*args, **kargs)
  File "/usr/local/bin/s4cmd.py", line 1632, in ls_handler
    self.pretty_print(self.s3handler().s3walk(args[1]))
  File "/usr/local/bin/s4cmd.py", line 129, in wrapper
    ret = func(*args, **kargs)
  File "/usr/local/bin/s4cmd.py", line 724, in s3walk
    pool.join()
  File "/usr/local/bin/s4cmd.py", line 594, in join
    self.tasks.join()
  File "/usr/local/bin/s4cmd.py", line 469, in join
    fail('[Thread Failure] ', exc_info=self.exc_info)
  File "/usr/local/bin/s4cmd.py", line 189, in fail
    raise RuntimeError(status)
RuntimeError: 1

  File "/usr/local/bin/s4cmd.py", line 1176, in s3walk
```

What would my next troubleshooting steps be?

**Comment by MRichards99** [comment]
Your access key isn't correct. `s4cmd` connects to AWS by default so if you're trying to connect to an alternative S3 system, you have to use `--endpoint-url https://my.s3.service.com`. For some reason, `s4cmd` doesn't use the `host_base` option in `.s3cfg`.
