### ISSUE TITLE
Timeout in EC2 when listing a bucket, s3cmd works.

### ISSUE THREAD

**Issue by marcelmfs** [bloomreach/s4cmd#49]
```
$  date; /usr/local/bin/s4cmd ls s3://my-redacted-bucket --debug; date
Thu Dec  3 17:16:53 UTC 2015
  (D)s4cmd.py:468  read S3 keys from $HOME/.s3cfg file
  (D)s4cmd.py:140  >> ls_handler(<__main__.CommandHandler object at 0x7fe855009a50>, ['ls', 's3://my-redacted-bucket'])
  (D)s4cmd.py:140  >> validate(<__main__.CommandHandler object at 0x7fe855009a50>, 'cmd|s3', ['ls', 's3://my-redacted-bucket'])
  (D)s4cmd.py:142  << validate(<__main__.CommandHandler object at 0x7fe855009a50>, 'cmd|s3', ['ls', 's3://my-redacted-bucket']): None
  (D)s4cmd.py:140  >> s3walk(<__main__.S3Handler object at 0x7fe855009a10>, 's3://my-redacted-bucket')
  (D)s4cmd.py:140  >> wrapper(<ThreadUtil(Thread-1, started daemon 140635834652416)>, <__main__.S3URL instance at 0x7fe854f7f950>, '', '', [])
  (E)s4cmd.py:359  [Errno 110] Connection timed out
  (D)s4cmd.py:140  >> wrapper(<ThreadUtil(Thread-2, started daemon 140635751315200)>, <__main__.S3URL instance at 0x7fe854f7f950>, '', '', [])
  (E)s4cmd.py:359  [Errno 110] Connection timed out
  (D)s4cmd.py:140  >> wrapper(<ThreadUtil(Thread-3, started daemon 140635740825344)>, <__main__.S3URL instance at 0x7fe854f7f950>, '', '', [])
  (E)s4cmd.py:359  [Errno 110] Connection timed out
  (D)s4cmd.py:140  >> wrapper(<ThreadUtil(Thread-4, started daemon 140635730335488)>, <__main__.S3URL instance at 0x7fe854f7f950>, '', '', [])
  (E)s4cmd.py:194  [Runtime Exception] [Errno 110] Connection timed out
  (E)s4cmd.py:196  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 337, in run
    self.__class__.__dict__[func_name](self, *args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 141, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 838, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/s4cmd.py", line 916, in s3walk
    for key in bucket.list(s3dir, PATH_SEP):
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
    encoding_type=encoding_type)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 472, in get_all_keys
    '', headers, **params)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 398, in _get_all
    query_args=query_args)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 110] Connection timed out

  (E)s4cmd.py:194  [Thread Failure] [Errno 110] Connection timed out
Thu Dec  3 17:51:27 UTC 2015
$
```

**Comment by chouhanyang** [comment]
Sometimes it is due to unable network connection or S3 throttling. Maybe you can try to play with --retry-delay and --retry to see if you they can help reduce the problem?

Also, check out the new s4cmd 2.0 with more robust boto3 API.
