### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/etc'

### ISSUE THREAD

**Issue by NK74** [bloomreach/s4cmd#86]
Hi,

issue on EC2 - ubuntu 14.04 

```
ubuntu@ip-172-31-35-159:~$ pip install s4cmd
Downloading/unpacking s4cmd
  Downloading s4cmd-2.0.1-py2-none-any.whl (149kB): 149kB downloaded
Downloading/unpacking pytz>=2016.4 (from s4cmd)
  Downloading pytz-2016.7-py2.py3-none-any.whl (480kB): 480kB downloaded
Downloading/unpacking boto3>=1.3.1 (from s4cmd)
  Downloading boto3-1.4.1-py2.py3-none-any.whl (121kB): 121kB downloaded
Downloading/unpacking jmespath>=0.7.1,<1.0.0 (from boto3>=1.3.1->s4cmd)
  Downloading jmespath-0.9.0-py2.py3-none-any.whl
Downloading/unpacking botocore>=1.4.1,<1.5.0 (from boto3>=1.3.1->s4cmd)
  Downloading botocore-1.4.60-py2.py3-none-any.whl (2.7MB): 2.7MB downloaded
Downloading/unpacking s3transfer>=0.1.0,<0.2.0 (from boto3>=1.3.1->s4cmd)
  Downloading s3transfer-0.1.7-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking docutils>=0.10 (from botocore>=1.4.1,<1.5.0->boto3>=1.3.1->s4cmd)
  Downloading docutils-0.12.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip_build_ubuntu/docutils/setup.py) egg_info for package docutils

    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking python-dateutil>=2.1,<3.0.0 (from botocore>=1.4.1,<1.5.0->boto3>=1.3.1->s4cmd)
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB): 201kB downloaded
Downloading/unpacking futures>=2.2.0,<4.0.0 (from s3transfer>=0.1.0,<0.2.0->boto3>=1.3.1->s4cmd)
  Downloading futures-3.0.5-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.7/dist-packages (from python-dateutil>=2.1,<3.0.0->botocore>=1.4.1,<1.5.0->boto3>=1.3.1->s4cmd)
Installing collected packages: s4cmd, pytz, boto3, jmespath, botocore, s3transfer, docutils, python-dateutil, futures
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/etc'

Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

Any idea ?

**Comment by NK74** [comment]
Resolved !

**Comment by MikeMcMahon** [comment]
HOWWWWW?

**Comment by ayrtonmassey** [comment]
Who were you, DenverCoder9? WHAT DID YOU SEE?!

Try `pip install --user -r requirements.txt`
